$ErrorActionPreference = "Stop"
$secretsUrl = "https://github.com/dungvuq1920-max/clickbank/settings/secrets/actions"
$actionsUrl = "https://github.com/dungvuq1920-max/clickbank/actions"

Write-Host "Create a Railway account/workspace API token:"
Write-Host "  https://railway.com/account/tokens"
Write-Host ""
Write-Host "Add it to GitHub Actions as:"
Write-Host "  Name:  RAILWAY_API_TOKEN"
Write-Host "  Value: your Railway API token"
Write-Host ""
Write-Host "Opening GitHub repository secrets..."
Start-Process $secretsUrl
Write-Host ""
Write-Host "After saving the secret, run the Deploy Railway Sites workflow:"
Write-Host "  $actionsUrl"
