import type { CatalogRole, ContentCatalog, SiteSlug, SiteStrategy } from './types';

const contentTypes = ['Guides', 'Reviews', 'Comparisons', 'Case Studies', 'Quizzes'];

function catalog(
  name: string,
  slug: string,
  role: CatalogRole,
  description: string,
  targetAudience: string,
  problemsSolved: string[],
  commercialIntent: string,
  affiliateOpportunities: string[],
  futureArticleIdeas: string[],
): ContentCatalog {
  return { name, slug, role, description, targetAudience, problemsSolved, commercialIntent, affiliateOpportunities, contentTypes, futureArticleIdeas };
}

export const catalogsBySite: Record<SiteSlug, ContentCatalog[]> = {
  'neuro-sleep': [
    catalog('Brain Performance Insights', 'brain-performance-insights', 'traffic', 'Search-led explainers for focus, memory, mental energy, and everyday brain wellness.', 'Readers researching brain fog, focus, or memory support.', ['Understand common focus blockers', 'Build realistic cognitive wellness expectations'], 'Awareness traffic that routes readers into routines and buyer guides.', ['Books and journals', 'Focus apps', 'Educational programs'], ['What Causes Brain Fog During a Busy Week?', 'How Sleep Quality Affects Daytime Focus', 'Deep Work vs Multitasking: What Helps Attention?', 'Morning Habits for Clearer Thinking', 'How to Build a Brain-Friendly Workday', 'Common Reasons Your Focus Drops After Lunch', 'Memory Support Habits for Adults Over 40', 'Digital Distraction and Cognitive Load Explained', 'How Stress Can Affect Mental Clarity', 'A Practical Guide to Tracking Focus Patterns']),
    catalog('Focus Systems Lab', 'focus-systems-lab', 'education', 'Beginner-friendly frameworks for building repeatable attention, productivity, and recovery routines.', 'Professionals and students who want a practical focus system.', ['Create a repeatable routine', 'Reduce tool overload', 'Track progress responsibly'], 'Educational content that introduces apps, planners, courses, and focus tools.', ['Productivity planners', 'Focus timers', 'Online courses'], ['How to Build a 7-Day Focus Reset', 'The Beginner Guide to Time Blocking', 'A Simple Deep Work Setup for Home Offices', 'How to Use a Focus Journal', 'Pomodoro vs Time Blocking: Which Fits You?', 'How to Plan Breaks Without Losing Momentum', 'A Beginner Guide to Digital Minimalism', 'How to Create an Evening Shutdown Routine', 'Focus Stack Basics: Habits Before Products', 'How to Measure Focus Without Overcomplicating It']),
    catalog('Sleep Reset Protocols', 'sleep-reset-protocols', 'solution', 'Actionable evening routines, sleep-environment checklists, and responsible product-led guides.', 'Readers looking for a calmer, more consistent night routine.', ['Improve sleep environment', 'Create wind-down habits', 'Compare practical sleep tools'], 'High-intent solution pages that connect routines with carefully framed product options.', ['Sleep accessories', 'Meditation apps', 'Wellness supplements'], ['The 7-Day Sleep Reset Checklist', 'How to Build a Calmer Bedroom Setup', 'Best Wind-Down Routine for Busy Professionals', 'Sleep Mask vs Blackout Curtains', 'How to Choose a White Noise Machine', 'A Practical Guide to Evening Screen Boundaries', 'Travel Sleep Kit Essentials', 'How to Evaluate a Sleep Support Supplement', 'Morning Light Routine for Better Sleep Consistency', 'Sleep Routine Mistakes to Avoid']),
    catalog('Cognitive Product Reviews', 'cognitive-product-reviews', 'review', 'Transparent reviews, alternatives, and comparisons for brain, focus, and sleep products.', 'Comparison shoppers evaluating wellness products before purchasing.', ['Compare features and tradeoffs', 'Check fit and limitations', 'Avoid exaggerated claims'], 'Commercial review hub for affiliate conversion.', ['Nootropic supplements', 'Sleep products', 'Focus software'], ['Best Focus Support Products: Buyer Guide', 'Best Sleep Support Tools Compared', 'Top Memory Support Supplements Compared', 'Focus App Comparison for Deep Work', 'Sleep Support Supplement Review Checklist', 'Best White Noise Machines for a Night Routine', 'Nootropic Alternatives for Beginners', 'Focus Planner Comparison Guide', 'Sleep Tracker Alternatives Compared', 'How to Read a Cognitive Supplement Label']),
    catalog('Brain & Sleep Assessment', 'brain-sleep-assessment', 'lead-generation', 'Quizzes, trackers, and printable resources that segment readers by their primary routine challenge.', 'Visitors unsure whether to prioritize focus, recovery, or sleep consistency.', ['Choose a starting point', 'Capture useful self-observations', 'Build a personalized routine'], 'Email opt-in hub that segments readers into relevant recommendations.', ['Email courses', 'Printable planners', 'Curated product bundles'], ['Take the Brain and Sleep Routine Quiz', 'Download the 7-Day Focus Tracker', 'Printable Evening Wind-Down Checklist', 'Which Focus Routine Fits Your Work Style?', 'Sleep Environment Scorecard', 'Brain Fog Pattern Worksheet', 'Deep Work Readiness Assessment', 'Weekly Mental Energy Planner', 'Travel Sleep Checklist', 'Focus Tool Buying Checklist']),
  ],
  'manifest-signal': [
    catalog('Manifestation Mindset', 'manifestation-mindset', 'traffic', 'Grounded explainers about intention, reflection, self-concept, and manifestation practices.', 'Curious readers exploring manifestation without unrealistic promises.', ['Understand core concepts', 'Separate reflection from hype'], 'Awareness content that routes readers toward practical rituals and programs.', ['Books', 'Journals', 'Meditation apps'], ['What Is Manifestation in Practical Terms?', 'Intention Setting vs Goal Setting', 'How Journaling Supports Self-Reflection', 'What Does Alignment Mean in Daily Life?', 'Morning Reflection Prompts for Clarity', 'How to Build a Consistent Gratitude Practice', 'Visualization for Beginners', 'Common Manifestation Myths Explained', 'How Self-Concept Shapes Daily Choices', 'A Grounded Guide to Abundance Journaling']),
    catalog('Alignment Practice Academy', 'alignment-practice-academy', 'education', 'Step-by-step spiritual reflection frameworks, journaling methods, and beginner rituals.', 'Beginners who want a calm and consistent personal-development practice.', ['Start without overwhelm', 'Create reflective habits', 'Stay grounded'], 'Educational path into journals, guided audio, and learning programs.', ['Guided journals', 'Audio programs', 'Personal-development courses'], ['How to Start a 5-Minute Alignment Ritual', 'Beginner Guide to Guided Journaling', 'How to Create a Reflection Corner at Home', 'A 7-Day Intention-Setting Practice', 'How to Use Affirmations Responsibly', 'Visualization Journal Setup Guide', 'How to Build a Morning Reflection Routine', 'Weekly Alignment Review Template', 'How to Choose Guided Meditation Audio', 'A Beginner Guide to Subconscious Reflection']),
    catalog('Ritual & Frequency Toolkit', 'ritual-frequency-toolkit', 'solution', 'Actionable ritual guides and product-led resources for readers seeking a structured practice.', 'Readers ready to test tools that support calm, reflection, and consistency.', ['Choose suitable tools', 'Build a ritual kit', 'Create sustainable routines'], 'Solution content connecting reader goals with relevant products.', ['Meditation tools', 'Guided audio', 'Ritual kits'], ['How to Build a Simple Manifestation Toolkit', 'Best Journaling Prompts for Morning Clarity', 'Guided Audio vs Silent Reflection', 'How to Choose a Meditation Cushion', 'A Calming Evening Ritual Checklist', 'Frequency Audio Listening Routine Guide', 'How to Use a Vision Board Thoughtfully', 'Desk Ritual Tools for Daily Reflection', 'How to Create a Digital Reflection Library', 'A Minimalist Spiritual Toolkit for Beginners']),
    catalog('Spiritual Program Reviews', 'spiritual-program-reviews', 'review', 'Responsible reviews and comparisons for manifestation courses, journals, audio, and reflection tools.', 'Buyers evaluating spiritual personal-development resources.', ['Compare program formats', 'Evaluate responsible messaging', 'Choose the right learning style'], 'Commercial review hub focused on fit, value, and realistic expectations.', ['Digital courses', 'Subscription apps', 'Guided journals'], ['Best Manifestation Programs Compared', 'Guided Journal Comparison for Beginners', 'Frequency Audio Programs: What to Evaluate', 'Manifestation Course Alternatives Compared', 'Best Meditation Apps for Reflection', 'Digital vs Printed Manifestation Journals', 'How to Review a Spiritual Development Program', 'Best Vision Board Tools Compared', 'Guided Audio Subscription Comparison', 'Beginner Manifestation Bundle Buyer Guide']),
    catalog('Alignment Assessment Studio', 'alignment-assessment-studio', 'lead-generation', 'Quizzes, templates, checklists, and printable rituals that guide the next reflective step.', 'Visitors who want a personalized place to begin.', ['Identify current priorities', 'Choose a practical ritual', 'Build an email-guided practice'], 'Lead generation hub segmented by clarity, routine, or self-reflection goals.', ['Email courses', 'Printable journals', 'Starter bundles'], ['Take the Alignment Style Quiz', 'Download the 5-Minute Ritual Template', 'Weekly Intention Planner', 'Which Journaling Style Fits You?', 'Reflection Routine Scorecard', 'Morning Clarity Checklist', 'Printable Vision Board Planning Sheet', '7-Day Alignment Email Challenge', 'Subconscious Reflection Prompt Pack', 'Choose Your Guided Audio Assessment']),
  ],
  'ai-hustle': [
    catalog('AI Opportunity Radar', 'ai-opportunity-radar', 'traffic', 'Search-led insights about AI tools, creator workflows, automation, and realistic online business experiments.', 'Beginners exploring practical ways to use AI online.', ['Understand use cases', 'Avoid trend chasing', 'Choose a realistic experiment'], 'Top-of-funnel content that routes readers toward workflows and software comparisons.', ['AI software', 'Creator tools', 'Educational products'], ['Best Beginner Uses for AI in a Side Hustle', 'What Is a Faceless Content Workflow?', 'AI Automation Ideas for Solo Creators', 'How AI Can Support Affiliate Content', 'Realistic AI Side Hustle Expectations', 'AI Tools vs Traditional Outsourcing', 'How to Validate an Online Business Idea', 'Common AI Tool Stack Mistakes', 'What to Automate First as a Beginner', 'How to Track an AI Workflow Experiment']),
    catalog('Operator Skills Academy', 'operator-skills-academy', 'education', 'Beginner tutorials for prompting, content operations, validation, publishing, and measurement.', 'Aspiring digital operators who need repeatable skills before more software.', ['Learn core workflows', 'Improve quality control', 'Build operational confidence'], 'Educational content that naturally recommends software and training.', ['Courses', 'Prompt libraries', 'Project tools'], ['Beginner Guide to Prompting for Content Research', 'How to Build a Simple Content SOP', 'How to Validate AI Output Before Publishing', 'Create a Weekly Operator Dashboard', 'How to Turn One Idea Into Five Content Assets', 'Beginner Guide to Faceless Short-Form Scripts', 'How to Build a Landing Page Brief With AI', 'How to Organize an AI Content Calendar', 'Email Funnel Basics for Side Hustles', 'How to Measure a Small Online Experiment']),
    catalog('Automation Workflow Stack', 'automation-workflow-stack', 'solution', 'Actionable systems for content production, lead capture, repurposing, and lightweight automation.', 'Creators ready to assemble a focused and affordable workflow.', ['Select a lean stack', 'Connect tools logically', 'Save time without sacrificing review'], 'Product-driven implementation guides for recurring SaaS affiliate revenue.', ['Automation SaaS', 'Email platforms', 'Content tools'], ['Build a Lean AI Content Stack', 'AI Research to Newsletter Workflow', 'Faceless Video Production Workflow', 'How to Automate Lead Magnet Delivery', 'Simple Affiliate Content Repurposing System', 'AI Blog Brief to Publish Checklist', 'How to Connect Forms to an Email Sequence', 'Beginner Social Scheduling Workflow', 'AI-Assisted Product Comparison Workflow', 'Monthly Tool Stack Audit Checklist']),
    catalog('AI Tool Review Desk', 'ai-tool-review-desk', 'review', 'Honest AI software reviews, alternatives, and comparisons organized by operator use case.', 'Tool-aware buyers comparing price, workflow fit, and learning curve.', ['Reduce software waste', 'Compare features by outcome', 'Choose tools for defined jobs'], 'High-commercial-intent SaaS review hub.', ['AI SaaS', 'Email SaaS', 'Automation platforms'], ['Best AI Writing Tools Compared', 'Best Automation Platforms for Beginners', 'AI Video Tool Comparison for Faceless Content', 'Email Platform Comparison for Side Hustles', 'Best Landing Page Builders Compared', 'AI Research Tool Alternatives', 'Best Social Scheduling Tools for Solo Creators', 'Prompt Library Tools Compared', 'AI Image Tool Buyer Guide', 'All-in-One AI Platforms vs Specialist Tools']),
    catalog('Side-Hustle Blueprint Studio', 'side-hustle-blueprint-studio', 'lead-generation', 'Quizzes, templates, SOPs, and stack planners for choosing a focused online experiment.', 'Visitors overwhelmed by too many possible AI business models.', ['Choose one model', 'Plan the first workflow', 'Capture leads by operator profile'], 'Lead generation hub feeding segmented software and training sequences.', ['Templates', 'Email courses', 'Software bundles'], ['Take the AI Operator Path Quiz', 'Download the Lean Tool Stack Planner', 'Faceless Content SOP Template', 'Weekly AI Experiment Scorecard', 'Which Side-Hustle Workflow Fits You?', 'AI Content Quality Checklist', 'Lead Magnet Funnel Map Template', 'Tool Budget Calculator for Beginners', '30-Day Operator Launch Checklist', 'AI Workflow Bottleneck Assessment']),
  ],
  'metabolic-reset': [
    catalog('Metabolism Knowledge Hub', 'metabolism-knowledge-hub', 'traffic', 'Responsible wellness explainers about routines, energy, appetite awareness, movement, and metabolism.', 'Readers looking for realistic weight-management education.', ['Understand sustainable habits', 'Avoid extreme claims', 'Build informed expectations'], 'Awareness traffic routed into healthy routine guides.', ['Books', 'Tracking apps', 'Wellness programs'], ['Metabolism Basics: A Responsible Beginner Guide', 'How Sleep and Routine Can Affect Daily Energy', 'Simple Ways to Build Meal Consistency', 'Why Sustainable Habits Matter More Than Quick Fixes', 'How to Track Hunger and Energy Patterns', 'Movement Snacks for Busy Days', 'How Stress Can Disrupt Healthy Routines', 'Beginner Guide to Balanced Meal Planning', 'What to Know Before Starting a Wellness Reset', 'How to Build a Supportive Progress Mindset']),
    catalog('Healthy Habit Academy', 'healthy-habit-academy', 'education', 'Beginner frameworks for meal preparation, movement, sleep consistency, and sustainable progress tracking.', 'Readers who want a routine that fits everyday life.', ['Start with manageable changes', 'Build consistency', 'Track habits without shame'], 'Educational content introducing plans, apps, trackers, and programs.', ['Meal planners', 'Fitness apps', 'Wellness courses'], ['How to Build a 7-Day Healthy Habit Plan', 'Beginner Guide to Meal Preparation', 'How to Create a Simple Movement Routine', 'A Non-Extreme Guide to Progress Tracking', 'How to Plan Healthy Snacks for Busy Days', 'Weekly Wellness Review Template', 'How to Build a Better Grocery Routine', 'A Beginner Guide to Habit Stacking', 'How to Set Realistic Wellness Goals', 'Evening Routines That Support Consistency']),
    catalog('Reset Routine Toolkit', 'reset-routine-toolkit', 'solution', 'Practical checklists and product-led guides for building a realistic wellness reset.', 'Readers ready to choose tools that make routines easier to sustain.', ['Simplify preparation', 'Support daily consistency', 'Evaluate wellness products responsibly'], 'Solution-focused hub for affiliate products and programs.', ['Kitchen tools', 'Fitness accessories', 'Wellness supplements'], ['The 7-Day Healthy Reset Checklist', 'Meal Prep Tools for a Simpler Week', 'How to Choose a Habit Tracking App', 'Beginner Home Movement Equipment Guide', 'How to Evaluate a Wellness Supplement', 'Water Bottle and Hydration Tracker Guide', 'Simple Lunch Prep Toolkit', 'Healthy Routine Starter Kit', 'How to Choose a Supportive Wellness Program', 'Travel Wellness Checklist']),
    catalog('Wellness Product Review Lab', 'wellness-product-review-lab', 'review', 'Safety-first reviews, comparisons, and alternatives for wellness products, supplements, tools, and programs.', 'Buyers comparing wellness resources without exaggerated promises.', ['Review fit and limitations', 'Compare value', 'Check responsible product claims'], 'Commercial review hub with clear disclaimers.', ['Supplements', 'Fitness products', 'Digital wellness programs'], ['Best Wellness Reset Programs Compared', 'Meal Planning App Comparison', 'Beginner Fitness Tracker Alternatives', 'How to Compare Wellness Supplements', 'Best Home Movement Tools for Beginners', 'Hydration Tracking Products Compared', 'Healthy Meal Planner Comparison', 'Wellness Program Review Checklist', 'Supplement Label Reading Guide', 'Best Habit Tracking Apps Compared']),
    catalog('Healthy Reset Assessment', 'healthy-reset-assessment', 'lead-generation', 'Quizzes, planners, trackers, and printable checklists that help readers choose one sustainable starting point.', 'Visitors unsure whether meals, movement, sleep, or preparation should come first.', ['Identify the first habit', 'Plan a realistic week', 'Build segmented email support'], 'Lead hub segmented around routine priorities.', ['Printable planners', 'Email challenges', 'Starter bundles'], ['Take the Healthy Reset Quiz', 'Download the 7-Day Habit Tracker', 'Weekly Meal Prep Planner', 'Which Wellness Habit Should You Start First?', 'Daily Energy Pattern Worksheet', 'Beginner Grocery Checklist', 'Movement Routine Scorecard', 'Hydration Habit Tracker', 'Healthy Routine Starter Template', '30-Day Consistency Calendar']),
  ],
  'love-psychology': [
    catalog('Relationship Psychology Insights', 'relationship-psychology-insights', 'traffic', 'Search-led relationship education about communication patterns, attraction, boundaries, and emotional clarity.', 'Adults seeking mature and practical relationship guidance.', ['Understand patterns', 'Reduce confusion', 'Build healthier expectations'], 'Awareness traffic routed into communication frameworks and resources.', ['Books', 'Journals', 'Learning programs'], ['What Healthy Communication Looks Like', 'Mixed Signals: Questions to Ask Yourself', 'How Boundaries Support Better Relationships', 'Emotional Availability Explained', 'How to Stop Overanalyzing Text Messages', 'Relationship Patterns Worth Noticing', 'Confidence vs Performance in Dating', 'How Values Shape Compatibility', 'What Secure Communication Can Look Like', 'When to Pause Before a Difficult Conversation']),
    catalog('Communication Skills Academy', 'communication-skills-academy', 'education', 'Beginner communication frameworks, conversation prompts, and boundary-setting guides.', 'Readers who want practical tools for calmer and clearer conversations.', ['Express needs respectfully', 'Listen with more clarity', 'Prepare for difficult conversations'], 'Educational content introducing books, courses, and communication tools.', ['Conversation cards', 'Courses', 'Guided journals'], ['How to Prepare for a Difficult Conversation', 'Beginner Guide to Healthy Boundary Language', 'How to Ask Better Dating Questions', 'Active Listening Basics for Couples', 'How to Communicate Needs Without Blame', 'Conversation Starters for New Relationships', 'Weekly Relationship Check-In Template', 'How to Handle a Misunderstanding Calmly', 'A Guide to Respectful Conflict Repair', 'How to Talk About Expectations Early']),
    catalog('Connection Repair Toolkit', 'connection-repair-toolkit', 'solution', 'Actionable tools and product-led resources for reflection, conversation planning, and relationship growth.', 'Readers looking for structured support for a current relationship challenge.', ['Choose a healthy next step', 'Use practical prompts', 'Create reflection routines'], 'Solution pages connecting readers with suitable resources while avoiding manipulative promises.', ['Relationship courses', 'Workbooks', 'Conversation tools'], ['A Conversation Repair Checklist', 'How to Build a Relationship Check-In Ritual', 'Best Conversation Card Formats Explained', 'Guided Journal Prompts for Emotional Clarity', 'How to Choose a Relationship Workbook', 'Boundary Planning Worksheet Guide', 'Date Night Planning Toolkit', 'How to Use a Couples Reflection Journal', 'Long-Distance Communication Toolkit', 'A Calm Conflict Preparation Checklist']),
    catalog('Dating & Relationship Reviews', 'dating-relationship-reviews', 'review', 'Balanced reviews and comparisons for dating guides, relationship programs, books, journals, and communication tools.', 'Buyers evaluating support resources before committing time or money.', ['Compare approaches', 'Avoid manipulative messaging', 'Choose resources that fit'], 'Commercial hub for ethical relationship affiliate offers.', ['Digital courses', 'Books', 'Subscription apps'], ['Best Relationship Communication Programs Compared', 'Dating Guide Alternatives for Adults', 'Conversation Card Sets Compared', 'Best Relationship Journals Compared', 'How to Evaluate a Dating Advice Program', 'Couples App Comparison Guide', 'Best Books for Better Communication', 'Long-Distance Relationship Resources Compared', 'Relationship Workbook Buyer Guide', 'Healthy Boundary Course Comparison']),
    catalog('Connection Clarity Assessment', 'connection-clarity-assessment', 'lead-generation', 'Quizzes, conversation templates, checklists, and reflective worksheets for choosing a healthier next step.', 'Visitors who need clarity before acting on a relationship concern.', ['Name the current challenge', 'Choose a conversation starting point', 'Segment email guidance responsibly'], 'Lead generation hub segmented by communication, boundaries, dating, or repair goals.', ['Email courses', 'Printable workbooks', 'Conversation bundles'], ['Take the Relationship Pattern Quiz', 'Download the Conversation Starter Sheet', 'Boundary Clarity Worksheet', 'Which Communication Style Needs Attention?', 'Weekly Relationship Check-In Template', 'Dating Values Checklist', 'Difficult Conversation Planner', 'Emotional Clarity Journal Prompts', 'Relationship Resource Buying Checklist', '7-Day Communication Reset Email Series']),
  ],
};

export const strategyBySite: Record<SiteSlug, SiteStrategy> = {
  'neuro-sleep': {
    brandMission: 'Help readers build clearer days and calmer nights through evidence-aware education and responsible product evaluation.',
    targetAudience: 'Busy adults researching focus, memory support, sleep quality, and sustainable cognitive wellness routines.',
    corePainPoints: ['Brain fog and inconsistent focus', 'Restless nights and low daytime energy', 'Confusing supplement and tool claims'],
    monetizationOpportunities: ['Sleep accessories', 'Cognitive wellness supplements', 'Focus apps', 'Courses', 'Email product sequences'],
    primaryKeywords: ['sleep quality', 'focus improvement', 'brain fog', 'memory support'], secondaryKeywords: ['deep work routine', 'sleep reset', 'focus habits'], commercialKeywords: ['best sleep support tools', 'best focus supplements'], reviewKeywords: ['sleep supplement review', 'focus app review'], comparisonKeywords: ['sleep mask vs blackout curtains', 'best focus apps compared'],
    affiliateProductCategories: ['Sleep accessories', 'Cognitive supplements', 'Focus apps', 'Trackers', 'Educational programs'],
    commissionPotential: { lowTicket: '$10-$40 accessories', midTicket: '$40-$150 supplements and devices', highTicket: '$150+ programs', recurring: 'Apps and replenishable wellness products' },
    suggestedLeadMagnet: '7-Day Focus & Sleep Reset Plan', suggestedQuiz: 'Brain & Sleep Routine Quiz', suggestedEmailFunnel: 'Quiz result -> routine guide -> educational sequence -> relevant comparison -> responsible product recommendation',
    searchIntentDistribution: { informational: 60, commercial: 30, transactional: 10 }, scores: { monetization: 8, seoDifficulty: 8, scalability: 9, launchPriority: 4 },
  },
  'manifest-signal': {
    brandMission: 'Offer grounded spiritual reflection tools that connect intention with consistent action.',
    targetAudience: 'Readers interested in manifestation, journaling, guided reflection, and personal-development rituals.',
    corePainPoints: ['Feeling blocked or scattered', 'Inconsistent reflective practice', 'Overhyped spiritual claims'],
    monetizationOpportunities: ['Digital programs', 'Guided journals', 'Meditation apps', 'Audio subscriptions', 'Email challenges'],
    primaryKeywords: ['manifestation', 'intention setting', 'journaling prompts', 'alignment ritual'], secondaryKeywords: ['visualization practice', 'guided reflection', 'self concept'], commercialKeywords: ['best manifestation program', 'best guided journal'], reviewKeywords: ['manifestation course review', 'frequency audio review'], comparisonKeywords: ['manifestation programs compared', 'digital vs printed journal'],
    affiliateProductCategories: ['Digital courses', 'Journals', 'Meditation apps', 'Guided audio', 'Ritual tools'],
    commissionPotential: { lowTicket: '$10-$40 journals', midTicket: '$40-$150 audio and courses', highTicket: '$150+ programs', recurring: 'Meditation and guided-audio apps' },
    suggestedLeadMagnet: 'Free 5-Minute Manifestation Ritual', suggestedQuiz: 'Alignment Style Quiz', suggestedEmailFunnel: 'Quiz result -> ritual template -> reflection prompts -> program comparison -> relevant recommendation',
    searchIntentDistribution: { informational: 65, commercial: 25, transactional: 10 }, scores: { monetization: 7, seoDifficulty: 6, scalability: 8, launchPriority: 3 },
  },
  'ai-hustle': {
    brandMission: 'Help aspiring digital operators build focused AI workflows without income hype or unnecessary software.',
    targetAudience: 'Beginners, creators, and affiliate operators testing realistic AI-assisted online workflows.',
    corePainPoints: ['Tool overload', 'No repeatable workflow', 'Unrealistic income promises'],
    monetizationOpportunities: ['Recurring SaaS', 'Automation platforms', 'Email tools', 'Courses', 'Template bundles'],
    primaryKeywords: ['AI tools', 'AI side hustle', 'AI automation', 'faceless content'], secondaryKeywords: ['AI workflow', 'content automation', 'AI operator'], commercialKeywords: ['best AI tools', 'best automation platform'], reviewKeywords: ['AI software review', 'email platform review'], comparisonKeywords: ['AI writing tools compared', 'automation platforms compared'],
    affiliateProductCategories: ['AI SaaS', 'Automation platforms', 'Email marketing tools', 'Landing page builders', 'Training programs'],
    commissionPotential: { lowTicket: '$10-$40 templates', midTicket: '$20-$150 SaaS plans', highTicket: '$150+ training', recurring: 'Strong recurring SaaS potential' },
    suggestedLeadMagnet: 'Free AI Operator Blueprint', suggestedQuiz: 'AI Operator Path Quiz', suggestedEmailFunnel: 'Quiz result -> lean stack planner -> workflow tutorial -> SaaS comparison -> use-case recommendation',
    searchIntentDistribution: { informational: 50, commercial: 40, transactional: 10 }, scores: { monetization: 9, seoDifficulty: 7, scalability: 10, launchPriority: 1 },
  },
  'metabolic-reset': {
    brandMission: 'Support realistic wellness habits with safety-first education and responsible product evaluation.',
    targetAudience: 'Adults seeking sustainable routines for weight management, energy, meals, and movement.',
    corePainPoints: ['Low energy', 'Inconsistent routines', 'Extreme or confusing wellness claims'],
    monetizationOpportunities: ['Wellness programs', 'Supplements', 'Kitchen tools', 'Fitness accessories', 'Tracking apps'],
    primaryKeywords: ['healthy habits', 'metabolism', 'weight management', 'wellness reset'], secondaryKeywords: ['meal prep routine', 'habit tracker', 'daily energy'], commercialKeywords: ['best wellness program', 'best habit tracking app'], reviewKeywords: ['wellness supplement review', 'fitness tracker review'], comparisonKeywords: ['wellness programs compared', 'habit tracking apps compared'],
    affiliateProductCategories: ['Wellness programs', 'Supplements', 'Meal-planning tools', 'Fitness products', 'Tracking apps'],
    commissionPotential: { lowTicket: '$10-$50 tools', midTicket: '$40-$150 products', highTicket: '$150+ programs', recurring: 'Replenishable wellness products and apps' },
    suggestedLeadMagnet: '7-Day Healthy Reset Plan', suggestedQuiz: 'Healthy Reset Quiz', suggestedEmailFunnel: 'Quiz result -> habit tracker -> supportive education -> buyer guide -> relevant product category',
    searchIntentDistribution: { informational: 65, commercial: 25, transactional: 10 }, scores: { monetization: 8, seoDifficulty: 9, scalability: 9, launchPriority: 5 },
  },
  'love-psychology': {
    brandMission: 'Provide mature relationship education that supports empathy, boundaries, and clearer communication.',
    targetAudience: 'Adults navigating dating, relationship communication, boundaries, and emotional clarity.',
    corePainPoints: ['Mixed signals', 'Difficult conversations', 'Unclear relationship patterns'],
    monetizationOpportunities: ['Relationship programs', 'Books', 'Journals', 'Conversation tools', 'Email courses'],
    primaryKeywords: ['relationship communication', 'dating psychology', 'healthy boundaries', 'relationship patterns'], secondaryKeywords: ['mixed signals', 'emotional availability', 'conversation starters'], commercialKeywords: ['best relationship program', 'best relationship journal'], reviewKeywords: ['dating guide review', 'relationship course review'], comparisonKeywords: ['relationship programs compared', 'conversation cards compared'],
    affiliateProductCategories: ['Digital courses', 'Books', 'Journals', 'Conversation tools', 'Relationship apps'],
    commissionPotential: { lowTicket: '$10-$40 books and cards', midTicket: '$40-$150 courses', highTicket: '$150+ programs', recurring: 'Apps and membership communities' },
    suggestedLeadMagnet: 'Conversation Starter Cheat Sheet', suggestedQuiz: 'Relationship Pattern Quiz', suggestedEmailFunnel: 'Quiz result -> conversation template -> educational sequence -> resource comparison -> relevant recommendation',
    searchIntentDistribution: { informational: 65, commercial: 25, transactional: 10 }, scores: { monetization: 7, seoDifficulty: 7, scalability: 9, launchPriority: 2 },
  },
};
