import type { Site, SiteSlug } from './types';
import { catalogsBySite, strategyBySite } from './content-architecture';

const now = '2026-05-29T00:00:00.000Z';

export const sites: Site[] = [
  {
    id: 'site_neuro_sleep',
    name: 'NeuroRestLab',
    slug: 'neuro-sleep',
    niche: 'Brain / Focus / Sleep',
    domain: 'NeuroRestLab.com',
    description: 'Science-inspired reviews for brain, focus, memory, and sleep products.',
    logo: 'NS',
    primary_color: '#111f3f',
    secondary_color: '#6d5dfc',
    accent_color: '#8dd8ff',
    theme: 'neuro',
    ctaTexts: ['Improve Sleep Tonight', 'Start Sleeping Better', 'Visit Official Website'],
    compliance: 'Do not make medical claims, promise cures, or guarantee health outcomes. Add a health disclaimer.',
    hero: '/assets/hero-brain-focus-sleep.png',
    leadMagnet: '7-Day Focus & Sleep Reset Plan',
    tagline: 'Evidence-aware wellness guidance for sharper days and calmer nights.',
    heroTitle: 'Upgrade Your Brain, Focus Deeper, Sleep Better',
    heroSubtitle: 'Science-inspired guides and responsible product reviews for focus, calm, memory support, and better rest.',
    primaryCta: 'Take the Brain & Sleep Quiz',
    secondaryCta: 'See Top Recommendations',
    painTitle: 'When your mind never fully resets, everything feels harder.',
    painPoints: [
      { title: 'Brain fog', text: 'Build a clearer routine around energy, attention, and sustainable cognitive support.' },
      { title: 'Restless nights', text: 'Explore practical sleep tools and habits without exaggerated health promises.' },
      { title: 'Low focus', text: 'Compare options for deep-work routines, recovery, and everyday consistency.' },
    ],
    pillars: [
      { title: 'Focus', text: 'Daily systems and tools designed to support concentration without overcomplication.' },
      { title: 'Sleep', text: 'Calmer evening routines, sleep-quality checklists, and careful product comparisons.' },
      { title: 'Cognitive Support', text: 'Evidence-aware guides for readers evaluating supplements, devices, and habits.' },
    ],
    productTypes: [
      { label: 'Routine', title: 'Sleep Support Tools', text: 'Compare practical tools for building a more consistent nighttime routine.' },
      { label: 'Guide', title: 'Focus Stack Reviews', text: 'Understand features, tradeoffs, and realistic expectations before buying.' },
      { label: 'Checklist', title: 'Cognitive Support Picks', text: 'Use a structured framework to compare everyday wellness options.' },
    ],
    categories: catalogsBySite['neuro-sleep'].map((catalog) => catalog.name),
    catalogs: catalogsBySite['neuro-sleep'],
    strategy: strategyBySite['neuro-sleep'],
    quizTitle: 'Find the right starting point for your brain and sleep routine.',
    quizText: 'Answer one quick question and get a practical next step based on your current priority.',
    faqs: [
      { question: 'Does NeuroRestLab provide medical advice?', answer: 'No. Our content is educational and should not replace advice from a qualified healthcare professional.' },
      { question: 'How are products reviewed?', answer: 'We focus on product positioning, practical fit, limitations, and questions to ask before purchasing.' },
      { question: 'Can a guide guarantee better sleep or focus?', answer: 'No. Outcomes vary. We prioritize sustainable habits and responsible expectations.' },
    ],
    disclaimer: 'Health disclaimer: NeuroRestLab provides educational content only. Consult a qualified healthcare professional before changing your wellness routine or using supplements.',
    created_at: now,
  },
  {
    id: 'site_manifest_signal',
    name: 'InnerAlignmentLab',
    slug: 'manifest-signal',
    niche: 'Spirituality / Manifestation',
    domain: 'InnerAlignmentLab.com',
    description: 'Manifestation, frequency, and subconscious growth reviews with grounded guidance.',
    logo: 'MS',
    primary_color: '#35195f',
    secondary_color: '#d6a84f',
    accent_color: '#f5dc89',
    theme: 'manifest',
    ctaTexts: ['Unlock Your Manifestation Potential', 'Discover The Method', 'Activate The Signal'],
    compliance: 'Do not guarantee spiritual, financial, or life outcomes. Position as personal development.',
    hero: '/assets/hero-spiritual-manifestation.png',
    leadMagnet: 'Free 5-Minute Manifestation Ritual',
    tagline: 'Grounded spiritual tools for reflection, intention, and meaningful personal growth.',
    heroTitle: 'Align Your Energy. Manifest With Clarity.',
    heroSubtitle: 'Explore spiritual tools, rituals, journals, and manifestation resources with a warm, grounded perspective.',
    primaryCta: 'Start Your Alignment Quiz',
    secondaryCta: 'Explore Manifestation Guides',
    painTitle: 'Clarity gets difficult when you feel blocked, scattered, or disconnected.',
    painPoints: [
      { title: 'Feeling blocked', text: 'Create gentle rituals that help you pause, reflect, and reconnect with your priorities.' },
      { title: 'Unclear intentions', text: 'Use journaling prompts to turn vague hopes into grounded next steps.' },
      { title: 'Disconnected routines', text: 'Explore tools that support reflection without making unrealistic promises.' },
    ],
    pillars: [
      { title: 'Clarity', text: 'Journaling prompts and reflective practices for more intentional decisions.' },
      { title: 'Energy', text: 'Simple rituals to create space for calm, attention, and emotional reset.' },
      { title: 'Manifestation', text: 'Grounded resources that connect personal vision with consistent action.' },
    ],
    productTypes: [
      { label: 'Journal', title: 'Guided Reflection Tools', text: 'Compare journals, prompts, and rituals for a more intentional daily practice.' },
      { label: 'Ritual', title: 'Alignment Resources', text: 'Explore accessible spiritual tools without extreme or fear-based messaging.' },
      { label: 'Course', title: 'Manifestation Guides', text: 'Evaluate programs through a grounded personal-development lens.' },
    ],
    categories: catalogsBySite['manifest-signal'].map((catalog) => catalog.name),
    catalogs: catalogsBySite['manifest-signal'],
    strategy: strategyBySite['manifest-signal'],
    quizTitle: 'Discover a ritual that fits where you are right now.',
    quizText: 'Choose your current focus and receive a simple alignment practice to begin with.',
    faqs: [
      { question: 'Is manifestation presented as a guaranteed result?', answer: 'No. We treat manifestation as a reflective personal-development practice, not a promise of specific outcomes.' },
      { question: 'Are the tools suitable for beginners?', answer: 'Yes. We favor accessible practices that can fit into a calm, realistic routine.' },
      { question: 'How do you choose recommendations?', answer: 'We look for clarity, practical use, responsible messaging, and a good fit for the intended reader.' },
    ],
    disclaimer: 'Personal development disclaimer: Spiritual practices are subjective. InnerAlignmentLab does not guarantee financial, relationship, or life outcomes.',
    created_at: now,
  },
  {
    id: 'site_ai_hustle',
    name: 'DigitalOperatorAI',
    slug: 'ai-hustle',
    niche: 'AI MMO / Side Hustle',
    domain: 'DigitalOperatorAI.com',
    description: 'AI tools, faceless content systems, and realistic side-hustle training reviews.',
    logo: 'AI',
    primary_color: '#080d0b',
    secondary_color: '#25b987',
    accent_color: '#8dffca',
    theme: 'ai',
    ctaTexts: ['Start Your AI Business', 'Get Instant Access', 'See The Training'],
    compliance: 'Do not promise income or guarantee earnings. Add an income disclaimer.',
    hero: '/assets/hero-ai-mmo.png',
    leadMagnet: 'Free AI Operator Blueprint',
    tagline: 'Practical AI workflows for building smarter, more focused online systems.',
    heroTitle: 'Build Smarter Side Hustles With AI',
    heroSubtitle: 'Tools, workflows, and honest reviews for AI-powered content systems and realistic online business experiments.',
    primaryCta: 'Explore the AI Tool Stack',
    secondaryCta: 'Get the Free Blueprint',
    painTitle: 'More tools do not create a better business. A clear system does.',
    painPoints: [
      { title: 'Tool overload', text: 'Cut through the noise and compare tools based on the job they actually perform.' },
      { title: 'No repeatable workflow', text: 'Map a simple path from idea to asset, distribution, and measurement.' },
      { title: 'Unrealistic promises', text: 'Evaluate training and software without fake income claims or shortcut language.' },
    ],
    pillars: [
      { title: 'Automate', text: 'Use AI where it saves time while keeping human review in the loop.' },
      { title: 'Create', text: 'Build useful content assets with repeatable workflows and clear quality checks.' },
      { title: 'Monetize', text: 'Test ethical offers and channels with realistic expectations and measurable inputs.' },
    ],
    productTypes: [
      { label: 'Stack', title: 'AI Tool Comparisons', text: 'Compare software by use case, complexity, and the workflow it supports.' },
      { label: 'Playbook', title: 'Operator Workflows', text: 'Turn scattered tactics into a focused sequence you can actually run.' },
      { label: 'Review', title: 'Training & SaaS Reviews', text: 'Assess value, tradeoffs, and fit before paying for another tool.' },
    ],
    categories: catalogsBySite['ai-hustle'].map((catalog) => catalog.name),
    catalogs: catalogsBySite['ai-hustle'],
    strategy: strategyBySite['ai-hustle'],
    quizTitle: 'Choose a workflow before you choose another tool.',
    quizText: 'Tell us your bottleneck and get a focused AI operator starting point.',
    faqs: [
      { question: 'Does DigitalOperatorAI promise income?', answer: 'No. We review tools and workflows, but earnings depend on many factors and are never guaranteed.' },
      { question: 'Are these guides beginner-friendly?', answer: 'Yes. We prioritize clear use cases, practical steps, and manageable tool stacks.' },
      { question: 'Do you recommend every AI tool?', answer: 'No. Our goal is to help readers avoid unnecessary software and choose tools with a defined purpose.' },
    ],
    disclaimer: 'Income disclaimer: DigitalOperatorAI does not guarantee earnings. Examples are educational and results depend on skills, effort, market conditions, and other factors.',
    created_at: now,
  },
  {
    id: 'site_metabolic_reset',
    name: 'HealthyResetLab',
    slug: 'metabolic-reset',
    niche: 'Weight Loss / Metabolism',
    domain: 'healthyresetlab.com',
    description: 'Fresh, responsible reviews for weight loss, metabolism, and healthy routine offers.',
    logo: 'MR',
    primary_color: '#174431',
    secondary_color: '#ff8a3d',
    accent_color: '#93e6aa',
    theme: 'metabolic',
    ctaTexts: ['Start Your Transformation', 'Boost Your Metabolism', 'Discover The Program'],
    compliance: 'Do not make medical claims, promise weight loss, or guarantee results. Add a health disclaimer.',
    hero: '/assets/hero-metabolic-reset.svg',
    leadMagnet: '7-Day Healthy Reset Plan',
    tagline: 'Supportive wellness guidance for realistic habits, steady energy, and healthier routines.',
    heroTitle: 'Reset Your Routine, Build Healthier Habits',
    heroSubtitle: 'Simple, responsible guides and product reviews for weight management, everyday energy, and metabolic wellness.',
    primaryCta: 'Take the Healthy Reset Quiz',
    secondaryCta: 'See Top Wellness Picks',
    painTitle: 'Progress becomes easier when your routine feels sustainable.',
    painPoints: [
      { title: 'Low energy', text: 'Explore manageable routines that support consistency instead of all-or-nothing thinking.' },
      { title: 'Persistent cravings', text: 'Build awareness around habits, meals, and practical preparation.' },
      { title: 'Slow progress', text: 'Focus on realistic wellness choices without shame, extremes, or guaranteed outcomes.' },
    ],
    pillars: [
      { title: 'Nutrition', text: 'Simple meal-planning habits and practical checklists for everyday consistency.' },
      { title: 'Movement', text: 'Supportive routines that encourage sustainable activity at your own pace.' },
      { title: 'Metabolic Wellness', text: 'Careful product reviews framed around safety, fit, and realistic expectations.' },
    ],
    productTypes: [
      { label: 'Plan', title: 'Healthy Habit Guides', text: 'Build a repeatable routine around meals, movement, sleep, and preparation.' },
      { label: 'Compare', title: 'Wellness Product Reviews', text: 'Review supplements and programs with a safety-first evaluation framework.' },
      { label: 'Tracker', title: 'Progress Checklists', text: 'Focus on habits you can measure without promoting extreme dieting.' },
    ],
    categories: catalogsBySite['metabolic-reset'].map((catalog) => catalog.name),
    catalogs: catalogsBySite['metabolic-reset'],
    strategy: strategyBySite['metabolic-reset'],
    quizTitle: 'Start with one realistic habit that fits your current routine.',
    quizText: 'Choose the area you want to simplify and receive a practical reset starting point.',
    faqs: [
      { question: 'Does HealthyResetLab offer medical advice?', answer: 'No. Our content is educational. Consult a healthcare professional for personal guidance.' },
      { question: 'Do you promote rapid weight-loss plans?', answer: 'No. We prioritize sustainable habits, responsible expectations, and non-shaming language.' },
      { question: 'Should I ask a professional before using supplements?', answer: 'Yes, especially if you have a health condition, take medication, or have specific dietary needs.' },
    ],
    disclaimer: 'Health disclaimer: HealthyResetLab provides educational information only. Consult a qualified healthcare professional before changing your diet, activity, or supplement routine.',
    created_at: now,
  },
  {
    id: 'site_love_psychology',
    name: 'ConnectionDecoded',
    slug: 'love-psychology',
    niche: 'Dating / Relationship',
    domain: 'connectiondecoded.com',
    description: 'Soft, practical relationship reviews focused on communication and emotional growth.',
    logo: 'LP',
    primary_color: '#7f1d3a',
    secondary_color: '#ff5c8a',
    accent_color: '#ffd0dd',
    theme: 'love',
    ctaTexts: ['Discover The Secret', 'Improve Your Relationship', 'Learn The Method'],
    compliance: 'Avoid manipulative language. Focus on communication, empathy, and relationship improvement.',
    hero: '/assets/hero-love-psychology.svg',
    leadMagnet: 'Conversation Starter Cheat Sheet',
    tagline: 'Mature, practical relationship guidance for clearer communication and stronger connection.',
    heroTitle: 'Understand Attraction. Communicate Better. Build Stronger Connections.',
    heroSubtitle: 'Dating and relationship guides, tools, and reviews grounded in empathy, psychology, and real-life communication.',
    primaryCta: 'Take the Relationship Pattern Quiz',
    secondaryCta: 'Read Dating Guides',
    painTitle: 'Healthy connection starts with clarity, not guessing games.',
    painPoints: [
      { title: 'Mixed signals', text: 'Look for communication patterns without overanalyzing every interaction.' },
      { title: 'Difficult conversations', text: 'Use practical prompts to express needs with confidence and respect.' },
      { title: 'Emotional confusion', text: 'Build stronger boundaries and choose resources that support healthy connection.' },
    ],
    pillars: [
      { title: 'Attraction', text: 'Understand connection through confidence, values, and honest communication.' },
      { title: 'Communication', text: 'Use thoughtful prompts and frameworks for conversations that matter.' },
      { title: 'Commitment', text: 'Explore relationship resources that encourage empathy, boundaries, and mutual respect.' },
    ],
    productTypes: [
      { label: 'Guide', title: 'Communication Toolkits', text: 'Find prompts and practical resources for clearer, more confident conversations.' },
      { label: 'Course', title: 'Relationship Program Reviews', text: 'Evaluate courses without manipulation, fear, or pickup-artist messaging.' },
      { label: 'Quiz', title: 'Pattern Awareness Tools', text: 'Reflect on recurring dynamics and choose healthier next steps.' },
    ],
    categories: catalogsBySite['love-psychology'].map((catalog) => catalog.name),
    catalogs: catalogsBySite['love-psychology'],
    strategy: strategyBySite['love-psychology'],
    quizTitle: 'Decode the pattern before you decide your next step.',
    quizText: 'Choose your current relationship challenge and get a healthier conversation starting point.',
    faqs: [
      { question: 'Do you teach manipulation or pickup tactics?', answer: 'No. We focus on confidence, empathy, honest communication, and healthy boundaries.' },
      { question: 'Can a guide guarantee a relationship outcome?', answer: 'No. Relationships involve two people. Our resources support reflection and better communication.' },
      { question: 'Are the recommendations suitable for difficult situations?', answer: 'Our content is educational. For abuse, safety concerns, or serious distress, seek qualified professional support.' },
    ],
    disclaimer: 'Relationship disclaimer: ConnectionDecoded provides educational content only. It is not therapy and does not guarantee any relationship outcome.',
    created_at: now,
  },
];

export function getSiteBySlug(slug: string): Site | undefined {
  return sites.find((site) => site.slug === slug);
}

export function getSiteById(id: string): Site | undefined {
  return sites.find((site) => site.id === id);
}

export function getRuntimeSite(): Site {
  const slug = (process.env.SITE_SLUG || 'neuro-sleep') as SiteSlug;
  return getSiteBySlug(slug) || sites[0];
}

export function getAdminSites(): Site[] {
  return process.env.APP_MODE === 'site' ? [getRuntimeSite()] : sites;
}

export function getRuntimeSiteId(): string | undefined {
  return process.env.APP_MODE === 'site' ? getRuntimeSite().id : undefined;
}
