export const sites = {
  admin: {
    key: 'admin',
    port: 3010,
    name: 'Affiliate Command Center',
    eyebrow: 'Central cPanel',
    hero: '/assets/hero-ai-mmo.png',
    headline: 'One control room for all three affiliate websites.',
    subhead: 'Generate previews, save drafts, push reviews, and track product links across every niche.',
    cta: 'Open cPanel',
    accent: '#f0b429',
    dark: '#172431',
    light: '#f9faf7',
    audience: 'Affiliate operator managing all three ClickBank microsites.',
    angle: 'central review generation, draft management, publishing workflow, product and affiliate link tracking.',
    tone: 'practical, organized, conversion-focused.',
    reviewPrompt: 'Central operator prompt for managing affiliate reviews across all websites.',
    imagePrompt: 'central affiliate dashboard, content calendar, product review workflow, clean premium workspace',
    formats: ['Central cPanel', 'Draft library', 'Push publishing'],
    examples: ['all sites', 'product links', 'affiliate links', 'review drafts'],
    offers: [],
    sections: [],
  },
  mind: {
    key: 'mind',
    port: 3011,
    name: 'NeuroSleep Review',
    eyebrow: 'Website 1: Brain / Focus / Sleep',
    hero: '/assets/hero-brain-focus-sleep.png',
    headline: 'Sharper focus by day. Deeper recovery by night.',
    subhead: 'A ClickBank affiliate hub for Brain Song reviews, sleep hacks, dopamine/focus content, and best memory supplement guides.',
    cta: 'Explore Brain Picks',
    accent: '#2f9cff',
    dark: '#132533',
    light: '#f4faf8',
    audience: 'Readers who want better focus, memory support, sleep quality, and practical brain-performance routines.',
    angle: 'Brain Song review, sleep hacks, dopamine focus blog, best memory supplements, no medical overclaiming.',
    tone: 'credible, clean, science-aware, friendly, no health guarantees.',
    reviewPrompt: 'Write a high-intent SEO review or landing page for a brain, focus, memory, dopamine, or sleep product. Extract the likely product promise from the URL and position it for readers comparing Brain Song, sleep hacks, dopamine/focus routines, or best memory supplements. Use careful language: support, may help, routine, guide; never claim treatment or guaranteed health outcomes. Include a quiz-funnel style CTA idea inside the article.',
    imagePrompt: 'brain focus sleep affiliate review, productivity desk, memory supplement bottle with no label, sleep routine, calm modern bedroom, premium editorial photo',
    formats: ['Blog SEO', 'Landing page', 'Quiz funnel'],
    examples: ['review Brain Song', 'sleep hacks', 'dopamine/focus blog', 'best memory supplements'],
    offers: [
      ['Brain Song Reviews', 'Long-tail SEO pages built around product review, benefits, complaints, pricing, and alternatives.'],
      ['Sleep Hacks', 'Short-video hooks like morning fatigue, racing thoughts, evening routine, and sleep reset checklists.'],
      ['Memory Supplements', 'Comparison-style content for best memory supplements, focus stacks, and ingredient explainers.'],
    ],
    sections: [
      ['Site type', 'Blog SEO, landing page, and quiz funnel for high-intent visitors.'],
      ['Traffic angles', 'Brain Song review, sleep hacks, dopamine/focus blog, best memory supplements.'],
      ['Affiliate funnel', 'TikTok/Reels hook -> quiz or SEO article -> product review -> CTA -> email follow-up.'],
    ],
  },
  spirit: {
    key: 'spirit',
    port: 3012,
    name: 'Manifest Signal',
    eyebrow: 'Website 2: Spiritual / Manifestation',
    hero: '/assets/hero-spiritual-manifestation.png',
    headline: 'Manifestation content that feels personal, polished, and persuasive.',
    subhead: 'An advertorial-first affiliate site for manifestation guides, frequency reviews, subconscious content, and VSL bridge pages.',
    cta: 'Read Manifestation Guides',
    accent: '#d6a84f',
    dark: '#123f46',
    light: '#f8f4eb',
    audience: 'Readers interested in manifestation, frequency concepts, subconscious reprogramming, journaling, and personal transformation.',
    angle: 'manifestation guides, frequency review, subconscious content, advertorial, long-form review, VSL bridge page.',
    tone: 'aspirational, calm, emotionally engaging, grounded, no absolute promises.',
    reviewPrompt: 'Write a story-led advertorial or long-form review for a spiritual manifestation product. Infer the product angle from the URL and connect it to manifestation guides, frequency review, subconscious content, journaling, personal transformation, and a VSL bridge page. Keep the tone emotional and aspirational but grounded; never promise guaranteed manifestation results.',
    imagePrompt: 'spiritual manifestation affiliate review, journaling ritual, candlelight, sound bowl, subtle crystal, subconscious transformation, premium editorial photo',
    formats: ['Advertorial', 'Long-form review', 'VSL bridge page'],
    examples: ['manifestation guides', 'frequency review', 'subconscious content'],
    offers: [
      ['Manifestation Guides', 'Story-led advertorials that connect frustration, desire, ritual, and product curiosity.'],
      ['Frequency Reviews', 'Review pages that explain the concept, who it suits, what to expect, and how to evaluate it.'],
      ['Subconscious Content', 'Faceless scripts around blocks, identity shifts, journaling prompts, and guided routines.'],
    ],
    sections: [
      ['Site type', 'Advertorial, long-form review, and VSL bridge page for warm emotional traffic.'],
      ['Traffic angles', 'Manifestation guides, frequency review, subconscious content, morning ritual hooks.'],
      ['Affiliate funnel', 'Reels/TikTok curiosity hook -> advertorial story -> VSL bridge -> affiliate CTA.'],
    ],
  },
  beauty: {
    key: 'beauty',
    port: 3013,
    name: 'AI Hustle Stack',
    eyebrow: 'Website 3: AI MMO / Side Hustle',
    hero: '/assets/hero-ai-mmo.png',
    headline: 'AI tools, faceless content, and side-hustle systems people can actually follow.',
    subhead: 'A tutorial and comparison affiliate site for AI affiliate tools, faceless TikTok workflows, automation content, and email capture funnels.',
    cta: 'Compare AI Tools',
    accent: '#25b987',
    dark: '#172431',
    light: '#f6fbff',
    audience: 'Beginners and creators who want AI-assisted affiliate workflows, faceless TikTok systems, automation tools, and side-hustle tutorials.',
    angle: 'AI affiliate tools, faceless TikTok, automation content, tutorial blog, tools comparison, email capture funnel.',
    tone: 'practical, direct, energetic, transparent, no income guarantees.',
    reviewPrompt: 'Write a practical tutorial review or tools comparison for an AI MMO, affiliate, faceless TikTok, automation, or side-hustle product. Infer the product from the URL and position it inside a workflow: AI affiliate tools, faceless content, short-form automation, email capture funnel, and beginner-friendly implementation. Never promise income; focus on process, testing, and realistic constraints.',
    imagePrompt: 'AI MMO side hustle affiliate review, laptop automation workflow, faceless TikTok phone setup, email funnel sketch, creator workspace, premium editorial photo',
    formats: ['Tutorial blog', 'Tools comparison', 'Email capture funnel'],
    examples: ['AI affiliate tools', 'faceless TikTok', 'automation content'],
    offers: [
      ['AI Affiliate Tools', 'Comparison posts for content generators, landing builders, email tools, tracking, and automation.'],
      ['Faceless TikTok', 'Tutorials for scripts, voiceover, editing, scheduling, hooks, and testing angles.'],
      ['Automation Content', 'Workflow posts that turn one product review into short videos, emails, and comparison pages.'],
    ],
    sections: [
      ['Site type', 'Tutorial blog, tools comparison, and email capture funnel for practical buyer intent.'],
      ['Traffic angles', 'AI affiliate tools, faceless TikTok, automation content, side-hustle workflow tutorials.'],
      ['Affiliate funnel', 'Tutorial video -> comparison article -> lead magnet -> email sequence -> affiliate tool CTA.'],
    ],
  },
};

export function getSite() {
  const key = import.meta.env.VITE_SITE_KEY || 'mind';
  return sites[key] || sites.mind;
}
